### ISSUE TITLE
Deep Linking doesn't work in already running app

### ISSUE THREAD

**Issue by farazs** [BranchMetrics/react-native-branch-deep-linking#116]
I'm not sure under what other circumstances this issue would occur, but I'm encountering it on Android in this scenario:

1. I have a webview running in my react native app
2. There is a link in the webview that matches the scheme for my app
3. The user clicks this link
4. An intent is received by the activity in `onNewIntent` and `this.setIntent(intent);` is called
5. Since the app is currently running and the activity is in the foreground, `onStart()` is never called and so `RNBranchModule.initSession(this.getIntent().getData(), this);` is not called. 
6. My `branch.subscribe()` callback is not called.

Moving `RNBranchModule.initSession(this.getIntent().getData(), this);` from `onStart` to `onNewIntent` fixes this but it seems like it would waste resources since everything is already initialized.

**Comment by jdee** [comment]
Hi @farazs. Thanks for getting in touch.

Calling `initSession` more than once is OK. The native SDK is smart enough to know it's already initialized and not reinitialize. It is supposed to be called whenever a new intent is received, via `onStart`. This is the route all inbound links take into the app. The problem, as I understand it, is that `onStart` is only called when an Activity becomes visible from a non-visible state. Ordinarily links come in from other apps, while your app is in the background. Then `onNewIntent` is called first. Later the Activity becomes visible, and `onStart` is called after the intent was changed. Moving the call to `initSession` into `onNewIntent` _may_ work, but this is not something we've tested thoroughly.

There's also reason to think this might not work on iOS. See https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html near the bottom under Preparing Your App to Handle Universal Links:

"It’s important to understand that if your app uses openURL: to open a universal link to your website, the link does not open in your app. In this scenario, iOS recognizes that the call originates from your app and therefore should not be handled as a universal link by your app."

However, links in a native iOS web view should open in the app, as discussed just above that. ("If the user taps a universal link from within an embedded SFSafariViewController, WKWebView, or UIWebView object, iOS opens your app.") So that could work if the RN WebView wraps a WKWebView or UIWebView on iOS. I remember having some trouble with something like this around iOS 7 using custom URIs, but it may work better now. In short, support for this use case may be spotty across the board. Universal Links and App Links are primarily intended as an inter-app linking mechanism, and it may be that this usage is not 100% supported at the native level.

I've done something like this before in native iOS development in an app that used Branch. But we did not embed short Branch links in the HTML in the web view. After all, you're probably first using Branch to shorten a link to your own domain, and then you have to use the Branch SDK to resolve it again, when you probably know what the underlying URL is in the first place. You do get the benefit of Branch analytics if you do this, but you have potentially two round trips to the Branch API over the network to make it happen. And if your app has an offline mode, Branch may not be able to resolve the link while the device is offline, so things may not work correctly, when you don't necessarily need the network to route a URL within the app.

I think the most efficient thing would be to use the [onShouldStartLoadWithRequest](https://facebook.github.io/react-native/docs/webview.html#onshouldstartloadwithrequest) property of the RN WebView and use bare links instead of Branch links. Then in that callback, you can just check the URL to see if it belongs to the app (using the domain, path, etc.). If it is your own URL, you can just route it and return false from the callback. If not, you return true, and the WebView will handle it. Something like:

```js
webview.onShouldStartLoadWithRequest = (event) => {
  if (!isMyOwnURL(event.url)) { // inspect the domain, path, etc.
    // external URL
    return true
  }

  // route the URL to a different view/component
  return false
}
```

Also note that if you set up Universal Links and/or App Links to your own domain in the app (in addition to the Branch domain), the `uri` field will be populated in the `branch.subscribe` callback with the non-Branch URL. On Android just make sure the two intent-filters are in the same Activity and on iOS, [add a branch_universal_link_domains key to your Info.plist](https://dev.branch.io/getting-started/universal-app-links/advanced/#custom-continueuseractivity-configuration) that includes your Branch domain and your own domain as well. Then you can open non-Branch links in the WebView and direct them into the app without calling the Branch API or hitting the network at all when opening the links.

Branch may be able to provide better support for this use case in the future, but right now it's probably going to cause you a bit of trouble, as you've seen.

**Comment by farazs** [comment]
Your suggestion is the solution I ended up going with. Instead of relying on branch to do the deep linking in-app, I just check the domain and route to it internally if it matches ours.

Thank you for your response! Shall I keep this issue open or close it?

**Comment by jdee** [comment]
I'm glad that resolved the issue for you. I'm closing this. Others with similar questions can still find closed issues in web searches and so on. Please get in touch again if you have further issues.

**Comment by bhatti-waqas** [comment]
You can work around with such issues using this plugin.
https://github.com/luisfcofv/react-native-deep-linking
