### ISSUE TITLE
Params are not coming back in iOS

### ISSUE THREAD

**Issue by jnrepo** [BranchMetrics/react-native-branch-deep-linking#118]
I'm having an issue where the `bundle` object passed into the callback only has `url` and nothing else. I'm passing in two test params in my deep link, yet they are not there. I'm noticing that this only happens on `test` mode, things look great on `live`.

```
  componentDidMount () {
    branch.subscribe(this.deeplinkCallback)
    Linking.addEventListener('url', this.deeplinkCallback)
  }

  deeplinkCallback = (bundle) => {
    console.log('deep link test', bundle)
    if (bundle && bundle.params && !bundle.error) {
      // grab deep link data and route appropriately.
    }
  }
```

That will log `'deep link test', { url: 'https://xxxx.test-app.link/test' }`

In my `AppDelegate.m`

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    return [RNBranch handleDeepLink:url] || [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation] || [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  }

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
  return [RNBranch continueUserActivity:userActivity] || [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}
```

Module Versions:
react-native: 0.38.1
react-native-branch: 0.9.5

Thanks in advanced!

**Comment by jdee** [comment]
@jnrepo Thanks for getting in touch. You may have some misconfiguration, and I think you can simplify the code a bit.

You don't need the call to `Linking.addEventListener`. I think that's where the callbacks are coming from with just the `url` property. You're using the same callback in both places, and the data model for each is a little different. `Linking.addEventListener` passes back an object with just a `url` property. `branch.subscribe` returns an object without a `url` property, only `error`, `params` and `uri`. You should not need to use `Linking` to receive link open events, and in Obj-C you don't need to call `[RCTLinkingManager application:continueUserActivity:restorationHandler:]` or `[RCTLinkingManager application:openURL:sourceApplication:annotation:]`.

I also suspect that something in your Info.plist may be misconfigured. Do you have a `branch_app_domain` key in your Info.plist? If so, is it set to `xxxx.test-app.link`? If it is set to something else, like `xxxx.app.link`, that might also be interfering. I don't think that key is necessary, but if it is present, it determines whether `[RNBranch continueUserActivity:]` returns YES or NO. It appears that it is returning NO, since you are getting the `Linking.addEventListener` callback. I think you can safely remove the `branch_app_domain` key.

Are you also handling Universal Links to your own domain in addition to the Branch `app.link` domain? Branch supports that without using `Linking`. All you have to do is add a `branch_universal_link_domains` key to the Info.plist. Make it an array, and add a string for each domain, e.g. `["xxxx.app.link", "xxxx-alternate.app.link", "xxxx.test-app.link", "xxxx-alternate.test-app.link", "example.com", "www.example.com"]`. Also be sure all those domains are in the app's Associated Domains entitlement entry in Xcode. Then the `branch.subscribe` callback will also be invoked for your non-Branch domains. The `uri` property in the callback is always populated with the original URL that opened the app, before Branch processing. For non-Branch links, the `params` will be null, but `uri` will have the non-Branch URL. For Branch links, `uri` is the same as the `~referring_link` field in the `params`.

Even if you're not handling non-Branch links, the `branch_universal_link_domains` key could provide another workaround for the issue if the `branch.subscribe` callback is not invoked. Just leave out the example.com entries.

If these things don't solve the problem, please let us know.

**Comment by jnrepo** [comment]
@jdee First off, thank you for that quick response.

I went and tried the things you said, but unfortuanately it is still returning with no params :/. I double checked for `branch_app_domain`, added in `branch_universal_link_domains`, and removed some code per your explanation.

Also this is on `Test`, on `Live` mode everything works as intended

**Comment by jnrepo** [comment]
Would doing this on a Simulator make a difference perhaps?

**Comment by jdee** [comment]
@jnrepo I've never gotten Universal Links to work in a simulator, though I read somewhere that it may be supported. I always test opening links on a device. (You can test certain things on a simulator, like generateShortUrl and showShareSheet.)

How are you using the test environment? Did you make `branch_key` in the Info.plist a dictionary with `test` and `live` entries as discussed [here](https://github.com/BranchMetrics/ios-branch-deep-linking#add-your-branch-key-to-your-project)? Or are you just changing the `branch_key` string entry to be your test key?

If you're using the dictionary approach, then you should also be sure to call `[RNBranch useTestInstance]`  immediately before `[RNBranch initSessionWithLaunchOptions:isReferrable:]` in your app delegate.

I haven't worked much with the test environment. I'll set that up with RN and see what happens.

**Comment by jnrepo** [comment]
@jdee 
Currently testing using both a Simulator and Mobile Device. I've found the code behaves the same for me in both places.

And yep exactly as listed in [there](https://github.com/BranchMetrics/ios-branch-deep-linking#add-your-branch-key-to-your-project) using a dictionary with two keys `live` and `test` each with the appropriate key value from Dashboard.

Also was not able to fix it with this line either
```
[RNBranch useTestInstance];
[RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```

**Comment by jnrepo** [comment]
@jdee FIGURED IT OUT! It was a complete config error 😅 , I did not realize the staging build was using a completely different Info.plist file. Thank you for your help. Closing this out!

**Comment by joesleiman** [comment]
I don't have a branch_app_domain key in myInfo.plist? @jdee . what should i do ?
