### ISSUE TITLE
showShareSheet function on BUO is undefined after upgrade from 1.0.5 to 1.1.0

### ISSUE THREAD

**Issue by JoarLeth** [BranchMetrics/react-native-branch-deep-linking#127]
After upgrading from `1.0.5` to `1.1.0` I can't call `showShareSheet` or the new `userCompletedAction` method on the object returned by `createBranchUniversalObject` as those are undefined. Do I need to do anything other than `npm install` when I've updated the version in my package.json file? I noticed that there is now an `async` keyword in front of the `createBranchUniversalObject` implementation. Does that have anything to do with it? Let me know if you need any more information.

**Comment by jdee** [comment]
@JoarLeth That's a shame. I apologize for the breaking change. This should have gone into 2.0. Most testing was done with the testbed apps in this repo, which for some reason were already using `await` with `createBranchUniversalObject`. Hence that app didn't break, and I didn't catch the problem.

The problem is that `createBranchUniversalObject` now makes a call into the native layer, and the only way RN allows this is via an async request. The call is fundamentally synchronous, but it has to be made async, like getLatestReferringParams and getFirstReferringParams. These should also be synchronous, but they are async because they call into the native layer.

So now `createBranchUniversalObject` returns a promise, not a BUO. You can do either:

```js
let buo = await branch.createUniversalObject(...)
```

or

```js
branch.createUniversalObject(...).then((buo) => {
  this.buo = buo
})
```

See the testbed apps for working examples.

I'll update the documentation to reflect this. Aside from the `userCompletedAction` method, that is the main change in 1.1.0, so anyone who can't immediately make these changes can just pin to 1.0.*.

**Comment by JoarLeth** [comment]
Thanks @jdee!
