### ISSUE TITLE
Error when trying to add Branch with React in Podfile

### ISSUE THREAD

**Issue by pyankoff** [BranchMetrics/react-native-branch-deep-linking#153]
Hi, I'm getting the following error when trying to follow instructions [here](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/installation.md#pod-only-installation)

```
[!] Unable to find a specification for `Branch-SDK` depended upon by `react-native-branch`
```

**Comment by jdee** [comment]
Hi @pyankoff. It sounds like you're getting 2.0.0-beta.1 from NPM or using the master branch from the repo. [These](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/Release-2.0.0.md#in-a-native-app-using-the-react-pod) are the instructions for 2.0.0. Please see the [testbed_native_ios](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/testbed_native_ios) and [webview_example_native_ios](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example_native_ios) projects in this repo for working examples of native iOS apps (one is Obj-C, the other Swift) with a RN component integrated. To run these apps on your own device, you just need to change the:

- bundle identifier
- dev team
- associated domains entitlement
- branch_key in the Info.plist

I think you'll have better luck with 2.0 than 1.1 because 1.1 has no support for routing links at the native level, which is probably what you'll be doing. A new NSNotification (RNBranchLinkOpenedNotification) was introduced in 2.0 (see both the examples above). I expect to release 2.0.0 to production within the next month. If you're just getting started, maybe this timing will work for you. If it doesn't, please let us know and we'll try to accommodate you.

I'm very interested in any and all feedback you may have. I've been spending time recently getting this to work properly on both iOS and Android.

**Comment by pyankoff** [comment]
Hi @jdee , thank you for quick reply! 
Yeah, I'm using 2.0.0-beta.1. Using `react-native link` seems to work just fine. 

Just looked at the instructions and projects you mentioned, my `pod install` error was due to the wrong path: "node_modules/react-native-branch" instead of "../node_modules/react-native-branch". Now pod install works too.

Thank you!

**Comment by vhoen** [comment]
Hi,

I am having the same trouble whenever I try `pod install`

`[!] Unable to find a specification for Branch-SDK depended upon by react-native-branch`

I am using react-native-branch@2.3.3.

`react-native link` worked just fine.

Any idea ? Thanks in advance.

**Comment by benmcmaster** [comment]
@vhoen did you figure it out?

**Comment by ericlewis** [comment]
@vhoen @benmcmaster it appears to be because the dependency in the podspec is `Branch-SDK` but branch's iOS pod is actually `Branch`.

**Comment by AngelDev727** [comment]
I am going to use "react-native-branch": "5.4.1",
After install library, when pod install, I am getting this error.

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a specification for `Branch (= 1.42.0)` depended upon by `react-native-branch`

How can I solve this issue?
