### ISSUE TITLE
[subdomain].app.link not working but not [subdomain]:// is working 

### ISSUE THREAD

**Issue by iDams** [BranchMetrics/react-native-branch-deep-linking#158]
Hey,

I have setup branch.io in my RN project following this [guide](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/setup.md)
RN 0.43.2
Branch 2.0.0-beta1

When I try in safari to copy paste the link like [subdomain].app.link, I get redirected to my fallback url. But when I do [subdomain]:// (the URI scheme I have registered in my info.plist), it opens the app. With subdomain equal to my URI scheme.

I might have done something wrong but I can't figure out what.
To be sure when you say this:
>Add applinks:xxxx.app.link and applinks:xxxx-alternate.app.link to the list. Make sure xxxx matches the 4 character subdomain for your app (you can find it on the dashboard here). If you use a custom subdomain, use that in place of the x's (eg imgur.app.link and imgur-alternate.app.link).

xxxx.app.link == the link domain in my dashboard/settings/link?

If someone has any input, it could be great!

Thanks!

**Comment by jdee** [comment]
Hi @iDams. Thanks for getting in touch. Sorry it's not working for you.

Have you clicked Enable Universal Links in the Dashboard? You should make sure that your bundle identifier and Apple App Prefix are set correctly, to agree with the settings in your project. As of iOS 9.2, iOS no longer supports custom URI redirects. You can open the app using a custom URI by typing it in manually in Safari, e.g., or programmatically using something like Linking.openURL() or UIApplication.openURL(). But a server cannot open an app with a redirect to a custom URI. You have to enable Universal Links. Also, Universal Links only work on a device, not a simulator.

Please let me know if that addresses the issue. Thanks.

**Comment by iDams** [comment]
Hey @jdee,

thanks for your reply.

>Have you clicked Enable Universal Links in the Dashboard?

Yep

I have set my Apple App Prefix and bundle identifier but I'm not sure the App Prefix is correctly linked to my app in Xcode (hope it makes sense). If it is linked with the bundle identifier then it is good.

> Also, Universal Links only work on a device, not a simulator.

Oh I see, so I should stop testing on my simulator.
On a real device, I don't need to use `Linking.openURL()` to open the app with a link right?
With Universal Link, the link created by Branch.io should open the app if I understood correctly?

Thanks for your help,

**Comment by jdee** [comment]
@iDams:

You can double-check your bundle identifier and app prefix if you want. Just grep for them in ios/MyProject.xcodeproj/project.pbxproj, e.g.:

```
[jdee@Jimmy-Dees-MacBookPro WebViewExample.xcodeproj (android-intent)]$ grep DEVELOPMENT_TEAM project.pbxproj
				DEVELOPMENT_TEAM = R63EM248DP;
				DEVELOPMENT_TEAM = R63EM248DP;
[jdee@Jimmy-Dees-MacBookPro WebViewExample.xcodeproj (android-intent)]$ grep PRODUCT_BUNDLE_IDENTIFIER !$
grep PRODUCT_BUNDLE_IDENTIFIER project.pbxproj
				PRODUCT_BUNDLE_IDENTIFIER = "io.branch.sdk.Branch-TestBed";
				PRODUCT_BUNDLE_IDENTIFIER = "io.branch.sdk.Branch-TestBed";
```

Those should be used for the Branch settings.

You do not need to use openURL(). You should just be able to tap the link on the device and open the app.

**Comment by iDams** [comment]
@jdee 

Thanks,
I've checked my bundle identifier and app prefix with your two commands. They are both good.
I've tested on a real device and links like https://[subdomain].app.link/something are still redirecting to my fallback url.

I've tried to put a `NSLog(@"HERE");` in both `openURL` and `continueUserActivity` methods in `AppDelegate.m` but nothing log in the console.
But no idea how to debug further...

**Comment by jdee** [comment]
@iDams: If the app is not launched, those methods will not be called. And I've had trouble using NSLog with RN. If you use RCTLog, you'll actually see the output:

```Obj-C
#import <React/RCTLog.h>

RCTLog(@"Opened URL %@", userActivity.webURL);
```

But it's not opening your app, so that's not useful yet.

Can you please try this?

1. Email a link to yourself.
2. Open that message in the iOS Mail app.
3. Long-press the link in the mail message (press and hold). This should display a menu.
4. Select _Open in "My App" App_. ("My App" will be the name of your app in quotes.)

If the menu doesn't show _Open in "My App" App_, then your Universal Links are not set up properly.

The only other thing you have to check besides the bundle identifier and app prefix is the Associated Domains entitlement:

https://dev.branch.io/getting-started/universal-app-links/guide/ios/#add-the-associated-domains-entitlement-to-your-project
https://github.com/BranchMetrics/ios-branch-deep-linking#support-universal-linking-ios-9

**Comment by iDams** [comment]
Hey @jdee,

I've tried the link in the iOS Mail app and and it is working.
I have the "Open in My App". And when I click on it, it opens my app!

This is weird because before trying in the iOS Mail app, I have tried in the Gmail App and it was not working, still opening Safari with my fallback url. But now, when I try the same link in Gmail app again or WhatsApp that was not working before, it works.

**Comment by jdee** [comment]
Hi @iDams. That sounds right. You can just enable Deepviews on the Dashboard Link Settings page or set `$ios_deepview` to `"branch_default"` (e.g.) in the control params. If the user ever taps the "app.link" breadcrumb to send links to Safari, they'll see that Deepview instead of being redirected to the App Store, and they'll be able to get back to the app.

**Comment by iDams** [comment]
@jdee,

Deepviews seems enabled by default. I didn't do anything and it's already enable.
<img width="725" alt="capture d ecran 2017-04-13 a 10 43 12" src="https://cloud.githubusercontent.com/assets/1591702/24997187/081b37fc-2036-11e7-91c4-7bc44493f6fa.png">

It seems this is not working then since when I couldn't open the app before, I was redirected to the fallback url not the deepview.
I have two questions:
1- How do I "unset" the link on my device? Now links always open the app and I'd like to be able to test deepviews.
2- If I want to set `$ios_deepview`, it's `https://[subdomain].app.link?$ios_deepview=branch_default`?
3- I'm trying to pass some params to redirect to the right page on my app. I tried with a link like this: `https://[subdomain].app.link?%24deeplink_path=test%2FmyParam` but on `branch.subscribe(bundle => ...)`, `bundle.params` is always null and `bundle.uri` contains the full link. I could parse it but it seems dirty to do this.

Thanks again for your help!
I really appreciate it

**Comment by jdee** [comment]
I only used Deepviews for the first time recently, and the UI in the Dashboard confused me too. You have to click one of the green Enable buttons to enable the Deepview. Only once it turns red and says Disable is it enabled. e.g., in this app the branch_default is enabled:

![screen shot 2017-04-13 at 8 04 05 am](https://cloud.githubusercontent.com/assets/121951/25010915/6ccd21b2-2020-11e7-8a7d-40eada974c6d.png)

As I understand it, which Deepview to use is, like many control parameters, either an app-wide setting in the Dashboard or a link-by-link setting in the control params. Once you enable Deepviews in the Dashboard, you don't need a $ios_deepview, just as you don't need a $ios_url or $android_url if you configure your App Store/Google Play redirect in the app settings.

1. You'll be directed to the $ios_deepview or $ios_url if the app is not installed or if you ever tap the "app.link" breadcrumb at the right side in the status bar with a small arrow. That takes you to Safari instead of the app. Once you tap that, your domain will always be directed to Safari until you either pull the web page down to reveal a Smart Banner with an Open in App option or long-press on the Get the App button at the bottom of the Deepview and select Open in App from the menu.

Regarding passing these parameters: How are you building your links? If you're building them in the app using a Branch Universal Object, you add $ios_deepview to the controlParams when you call showShareSheet or generateShortUrl. If you are generating links in the Dashboard, you can set them there in the Redirects tab when you edit/create the link. There's a pulldown for each platform with a Deepview option.

![screen shot 2017-04-13 at 8 24 16 am](https://cloud.githubusercontent.com/assets/121951/25011548/a95cff24-2022-11e7-89e7-585af8679afb.png)

You can add query parameters to a link, but that's not the usual way to pass control parameters.

See the webview_example in this repo for a working example of an app that shares content and routes the links it generates. See App.js for an example of [branch.subscribe](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/App.js#L14) and Article.js for [BUO creation/view event registration](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/Article.js#L34) and [sharing](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/Article.js#L70).
