### ISSUE TITLE
Jest - Cannot read property 'setDebug' of undefined

### ISSUE THREAD

**Issue by iDams** [BranchMetrics/react-native-branch-deep-linking#161]
Hey,

I have this error when running tests with jest

<img width="837" alt="capture d ecran 2017-04-14 a 17 29 57" src="https://cloud.githubusercontent.com/assets/1591702/25047631/35b37096-2138-11e7-9db7-5d10c95905cc.png">

Do we have to mock something to make it works with jest?

Thanks,

**Comment by jdee** [comment]
Hi @iDams. I think this is the same as #119. I asked for more detail there, never got it, and closed the issue. But now I guess I can see roughly what's going on. The NPM module itself uses ava. It mocks the native RNBranch module. You can run `npm test` in this repo and see the one test case succeed. See [test/helpers/RNBranch.mock.js](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/test/helpers/RNBranch.mock.js). The RNBranchEventEmitter module was introduced in the master branch and hasn't been released yet, so you don't need that unless you're using master or 2.0.0-beta.1. The RNBranchEventEmitter will be released with 2.0.0-beta.2 soon, and then users of 2.0.0 will need it.

If there's a generic way of adding these mocks to the NPM module so that users don't have to add them, I'd like to do that and make this easier for everyone. For now, if you introduce your own mock, that will probably fix this issue for you.

**Comment by iDams** [comment]
Thanks for your reply @jdee. Sorry I didn't see #119.

I fixed it with adding `RNBranch: {}` in `/node_module/react-native/jest/setup.js` in the `mockNativeModules` object.
Sounds weird to have to add something in `react-native` but seems to work for now.
