### ISSUE TITLE
[iOS] $deeplink_url not working as expected

### ISSUE THREAD

**Issue by farazs** [BranchMetrics/react-native-branch-deep-linking#186]
According to this doc https://dev.branch.io/getting-started/universal-app-links/advanced/ios/#how-to-handle-uri-paths-with-universal-links when a branch link is opened with a `$deeplink_url` provided, this should be the URL passed to the handler (in this case to `branch.subscribe(handler)`. This works as expected on Android, but on iOS the original URL `xxxx.app.link` is passed.

I am currently using version `1.0.4` but I think the issue is also there in the v2 beta. I believe the code at https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/ios/RNBranch.m#L86 needs to be modified to handle this or the user should be able to define their own deep link handler.

**Comment by jdee** [comment]
Hi @farazs. Thanks for getting in touch.

I think that part of the problem is those instructions need to be corrected for RN. You've linked to the iOS Advanced page. Unfortunately, the RN Advanced page is just a copy of the iOS Advanced page: https://dev.branch.io/getting-started/universal-app-links/advanced/react/. I don't think there should be anything special needed to use the `$deeplink_path` (or `$ios_deeplink_path` or `$android_deeplink_path`) with the react-native-branch SDK.

The `uri` parameter passed to the `branch.subscribe` callback is not routable (on either platform) for Branch links. In the case of Universal Links or App Links, the `uri` field is always the original short URL that opened the app, e.g. `https://myapp.app.link/xyz`. For custom URIs it should always be `urischeme://open?link_id=xxxx`. These links are opaque and require the Branch API to do a lookup in order to resolve them into the parameters you provided when you constructed the link. I think this is probably accidentally being populated on Android with the $deeplink_path that you specified. On Android, perhaps the app is opened with `urischeme://$deeplink_path`, and then that is passed back in `uri` as a non-Branch link (with `params: null`). On iOS, you're just opening a `xxxx.app.link` Universal Link because since iOS 9.2, URI redirects from a server aren't supported.

I did a little testing and wasn't able to produce anything unexpected. It may be that there's something in your app configuration that results in the Android behavior you reported.

You have to consult the `params` to determine what to do with any Branch link. You should be able to see the `$deeplink_path` parameter in `params.$deeplink_path` as well as `params.$ios_deeplink_path`, `params.$android_deeplink_path`, etc., if you have set them, just like all the other `params`. There you can do what you like with the `$deeplink_path` or any of the other params.

**Comment by farazs** [comment]
Ah that makes sense. We should handle the params ourselves. I was confused because it seemed to be different for Android but it's probably something with my configuration. Thanks for the help!
