### ISSUE TITLE
ios - failed to compile application with new version

### ISSUE THREAD

**Issue by guysegal** [BranchMetrics/react-native-branch-deep-linking#195]
I'm trying to integrate the new version (2.0.0-beta3) to our app without success. 

I got this error:

<img width="721" alt="screen shot 2017-04-30 at 16 24 45" src="https://cloud.githubusercontent.com/assets/7164560/25564713/c76da9ee-2dc1-11e7-9cc3-768812b5ac1f.png">

Our app uses Swift dependencies so our Podfile declares `use_frameworks!`, after some investigation I remembered about this PR - https://github.com/BranchMetrics/react-native-branch-deep-linking/pull/22 - that was submitted by one of my teammates.

This PR enables projects that declares `use_frameworks!` to cosume react-native-branch - without 'React' dependency in the podspec it can't work.

I noticed that few month after this PR revered the fix - https://github.com/BranchMetrics/react-native-branch-deep-linking/pull/77 - was there any particular reason to do it?

I added the 'React' dependency in react-native-branch package of 'webview_example_native_ios' and it compiled succesfully.

This is a blocker for apps that use Swift and react-native like us, is it possible to bring back the dependency? I'm open the other solution as long as it works

**Comment by guysegal** [comment]
After some investigation I found out that our app declares `use_frameworks!` in the Podfile.
I guess that's the reason react-native-branch dosen't recognize the React pod.
Is there a way to make react-native-branch to identify React pod in that way?

**Comment by guysegal** [comment]
see also my fork - I changed the podfile of `webview_example_native_ios` - now when you compile it the same error is shown (notice that RN version is 0.42 due to yoga changes)

https://github.com/guysegal/react-native-branch-deep-linking/blob/master/examples/webview_example_native_ios/Podfile

**Comment by jdee** [comment]
Hi @guysegal. Thanks for getting in touch, and apologies for the delay. I'm not sure what the reason was for that original PR. I was new to the project and wrestling dependencies on a number of fronts.

Until now I didn't think it was really feasible to build an RN app with Swift since the React pod itself fails to build when `use_frameworks!` is specified because of a yoga header. This ruled out any use of Swift pods or imports and required a bridging header, making it prohibitive for a lot of apps. In addition, with RN 0.42, the React pod couldn't even be installed because of yoga. I finally found [this](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#podfile):

```Ruby
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
```

This seems to solve both problems. I'm not sure if that's a recent addition to the docs or just something I missed before, but 0.42 is pretty recent, and without this, even earlier versions won't build with `use_frameworks!`.

I've converted webview_example_native_ios to be a proper Swift app again, restoring some Swift pods that were removed, and it works fine now.

I'll get this released probably in the next day or two, but definitely by the end of the week. For now, the master branch should improve matters for you.

**Comment by guysegal** [comment]
Thank you very much! Now we'll be able to upgrade to the newest versions 
Looking forward for the npm release.
