### ISSUE TITLE
branch.subscribe calls twice

### ISSUE THREAD

**Issue by khagesh** [BranchMetrics/react-native-branch-deep-linking#227]
`react-native`: `0.44`
`react-native-branch`: `2.0.0-beta.6`
`ios`: `9.3` (I can confirm by tomorrow if it happens on ios 10 as well)

*Scenario*
I install the app using sms link, opens the app and `branch.subscribe` gets called with correct data. However, as soon as user sees push notification permission request pop up, `branch.subscribe` is called again, but this time with no deep link data association.

I tried pushing delaying asking push notification permission once we move to another view, but no at what point in onboarding I move push permission, `branch.subscribe` gets called again.

Is there any way I can workaround this issue?
Please let me know if you need more details around this issue.

**Comment by jdee** [comment]
Hi @khagesh. What you're seeing is basically by design. The underlying native SDKs work the same way. The callback is not called only when a user opens a link. It is called any time the SDK makes a call to the Branch API. This is largely to support deferred deep linking. When the app is launched, it may be a new install from a Branch link. In that case, the response from the API to the initialization call will contain deep link data. In most cases, it doesn't. If the response does not include a deep link, you get a `subscribe` callback at initialization with `{ error: null, params: { "+clicked_branch_link": false", "+is_first_session": false } }`. This is the same behavior as the iOS and Android SDKs. There are times other than initialization when the API has to check for a deferred deep link. For example, it does this every time the app enters the foreground. In most cases, the callback will be invoked, but no link will have been clicked. You can just ignore the callback in these cases. See the `webview_example` in the repo, which handles this. Basically you can do this:

```js
branch.subscribe(({ error, params}) => {
  if (error) {
    // an error occurred. handle the error (log, etc.), but don't continue
    return
  }

  // params is never null if error is null

  if (!params["+clicked_branch_link"] && !params["+non_branch_link"]) {
    // this is one of those responses you can ignore
    return
  }

  // If you are also using Branch to handle your non-Branch links, they will appear
  // as params["+non_branch_link"].
  if (params["+non_branch_link"]) {
    handleNonBranchLink(params["+non_branch_link"])
  }
  else {
    // get data for the Branch link from the params.
    // params["~referring_link"] will be the Branch link that opened the app.
    handleBranchLink(params)
  }
})

function handleNonBranchLink(url) {
  // handle links to your own domain here
}

function handleBranchLink(params) {
  // get any relevant data, including metadata, from the params to handle the link
}
```

I'd like to add more semantic distinction to this SDK so that you can receive different callbacks or subscribe to different events to make it easier to distinguish these cases. But this is how it works today.

**Comment by khagesh** [comment]
Thank you so much for detailed explanation. I understand that it is the inherent behaviour. Here is how I was handling it and the reason it is creating issue just for my case. 

```js
if (params["+clicked_branch_link"] && params.token) {
  // handle branch data
  redux.setToken(params.token)
} else {
  // no branch data passed, set blank for token
  redux.setToken(null)
}
```
If you focus just a bit on `else` block, this is the block which creates issues the second time. As soon as user gives permission for push notification, `subscribe` is called again, this time with without any token which resets the token. I was thinking if there is anyway sdk provide the same data on second subscribe because we opened it via SMS link and it data once we opened it.

Again thank you looking into it. May be I can think of some workaround on my end.

**Comment by jdee** [comment]
I think it would be an error to pass the same parameters again. This would appear the same to the app as a user opening the same link again. Basically the purpose of that callback function is to tell you that a link was opened. However, it is called at other times without link data. If there is no error, and no link was clicked, the only information you have is that something happened somewhere, but nothing is wrong, and there's nothing to do. In other words, a meaningless event has been triggered. It's probably safest to do nothing in the else except at most log a message (or just add something like `if (!params['+clicked_branch_link']) return` early in the callback).

The question is when does `redux.setToken(null)` need to be called? Is this ever working correctly? Is the idea to set the token at launch, either to the value from an initial link or null? In that case, can you just set it to null in your `componentWillMount` and then set it non-null afterward if a link is opened? If you can't first set it to null and then non-null later, you can also track the state and wait for `branch.subscribe` to return the first time, e.g.

```js
componentWillMount() {
  this.branchInitialized = false
  branch.subscribe(({error, params}) => {
    if (error) {
      console.error('Error from Branch: ${error}')
      return
    }

    // in case of non-Branch links, remove the comment
    if (!params['+clicked_branch_link'] /* && !params['+non_branch_link'] */) return

    if (this.branchInitialized) return
    redux.setToken(params.token) // null in case +clicked_branch_link is false
    this.branchInitialized = true
  })
}
```

I think this might be a little easier if we added multiple events rather than using a single callback. Then you could do something like:

```js
// params.token would be null in case of launch without a link open
branch.addEventListener('initSuccess', (params) => redux.setToken(params.token))
branch.addEventListener('initError', (error) => console.error('Error initializing Branch: ${error}'))
branch.addEventListener('openSuccess', (params) => {
  // route the link to the appropriate component based on the params
})
branch.addEventListener('openError', (error) => console.error('Error opening Branch link: ${error}'))
```

This should make it into an upcoming release, after 2.0. For now, I'd recommend relocating the code in your else block.

**Comment by khagesh** [comment]
Thanks for detailed explanation and I think adding separate events will definitely help.

> The question is when does redux.setToken(null) need to be called? Is this ever working correctly? Is the idea to set the token at launch, either to the value from an initial link or null? In that case, can you just set it to null in your componentWillMount and then set it non-null afterward if a link is opened? If you can't first set it to null and then non-null later, you can also track the state and wait for branch.subscribe to return the first time

This is same think I also thought, because I would need to set it to null. Main reason is because if we have the token we redirect user to some screen and if we don't have token we redirect to other screen.
