### ISSUE TITLE
Manual linking install option v1.1.1  has Branch.h file not found error

### ISSUE THREAD

**Issue by PrimeLens** [BranchMetrics/react-native-branch-deep-linking#229]
The 1.1.1 docs lists install options as Cocoapods, Carthage or Manual Linking. 
I chose manual linking as I would prefer to avoid bringing in another technology just for branch. Also I am familiar with the manual linking process as I used it on react-native-onesignal and react-native-intercom. Since its listed as an option in the docs I hoped it would work. 

- My dependencies are below as per a recent installation react native init.
- I've carefully followed the linking instructions carefully listed here on [FB docs](http://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) 
- (I know its not necessary for 1.1.1 but) I also added `$(SRCROOT)/../node_modules/react-native-branch/ios` to the header search paths just in case that would fix it but it didn't

    "dependencies": {
      "react": "16.0.0-alpha.12",
      "react-native": "^0.46.3",
      "react-native-branch": "^1.1.1",
      "react-native-intercom": "^6.2.0",
      "react-native-onesignal": "^3.0.4"
    }

<img width="1045" alt="branch error" src="https://user-images.githubusercontent.com/636249/28422809-2b22b4e8-6d37-11e7-8224-65ed7b20808d.png">

**Comment by jdee** [comment]
Hello, @PrimeLens. Thanks for getting in touch. Have you tried using 2.0.0-beta.7? Technically it's a beta release, but it's been in beta for months. It's pretty solid and nearing a production release. The main things left to do involve automation, so that there's less setup. I don't anticipate significant changes to the code itself. In particular, in 2.0.0 the native Branch SDKs are included in the NPM package so that there is no external dependency. There is no need for CocoaPods, Carthage or manual SDK installation. See https://rnbranch.app.link/version-2#sdk-integration. At any rate, since the prod release is coming soon, it might be a good idea to look at version 2, even if you cannot use it until the prod release is out.

Also, I see something odd in your screenshot. I don't understand why you have Branch.framework as well as libBranch.a (twice). These are likely to conflict at link time or at best produce unpredictable results once you get past the header issue.

While CocoaPods really does take over the project and make lots of changes, Carthage is not very intrusive. It essentially just makes the manual integration process a bit simpler. If you have to use 1.1.1, Carthage may be an easier option.

In the examples folder in this repo, testbed_carthage illustrates integration of 1.1.1 using Carthage. testbed_simple and webview_example both use 2.0.0 (the master branch) and `react-native link`, with no extra step to integrate the Branch SDK.

The goal of 2.0 is to get you out of Xcode and Android Studio so that you don't have to do things like this anymore. Whether immediately or soon, I think 2.0 will be the long-term solution to this problem.

**Comment by PrimeLens** [comment]
Thanks for the prompt reply!
I plan to look at v2 and think it is a step in the right direction, do you have an estimated date when it will be released on npm?
Also if I want to use 1.1.1 and I want to use manual linking how do I get around the error in the original post?

**Comment by jdee** [comment]
2.0.0 has been released to production. I'd urge you to update when you can. Getting past this sort of problem was one of the motivations for a lot of the changes in 2.0.
