### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by chenyanji** [BranchMetrics/react-native-branch-deep-linking#230]
react-native-cli: 2.0.1
react-native: 0.46.4
react-native-branch：2.0.0-beta.7

I am based on https://github.com/BranchMetrics/react-native-branch-deep-linked/blob/master/docs/Release-2.0.0.md#in-a-native-app-using-the-react -pod configuration

error：

duplicate symbol _OBJC_IVAR_$_BranchOpenRequest._callback in:
    /Users/shenying/Library/Developer/Xcode/DerivedData/TestApp-chqltrqtnrcbjyaunlfagfxkaznz/Build/Products/Debug-iphonesimulator/Branch-SDK/libBranch-SDK.a(BranchOpenRequest.o)
    /Users/shenying/Library/Developer/Xcode/DerivedData/TestApp-chqltrqtnrcbjyaunlfagfxkaznz/Build/Products/Debug-iphonesimulator/libreact-native-branch.a(BranchOpenRequest.o)
ld: 404 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Simulator error: Cannot read property 'ADD_TO_CART_EVENT' of undefined

**Comment by chenyanji** [comment]
@jdee

**Comment by jdee** [comment]
Hi @chenyanji. Thank you for the report. If you updated from an older release of this SDK, did you also remove the "Branch" pod from your Podfile in favor of the "Branch-SDK" pod from the NPM module? https://rnbranch.app.link/version-2#using-the-react-pod. Basically you cannot have both

```Ruby
pod "Branch'
```

and

```Ruby
pod "Branch-SDK", path: "../node_modules/react-native-branch/ios"
```

in your Podfile, or you'll get this kind of error. I suspect something like this is causing the error.

**Comment by chenyanji** [comment]
@jdee  

I started from 2.0, did not use 1.0

Podfile file contents:

Pod "React", path: "../node_modules/react-native"
# The following line is necessary with use_frameworks! Or RN> = 0.42.
Pod "Yoga", path: "../node_modules/react-native/ReactCommon/yoga"
Pod "react-native-branch", path: "../node_modules/react-native-branch"
Pod "Branch-SDK", path: "../node_modules/react-native-branch/ios"

**Comment by jdee** [comment]
@chenyanji Are you also using `react-native link`? I've heard of apps doing this. To be honest, I think it's a mistake. I'm not really a React Native expert, so I may be wrong. But I believe the only real reason to use the React pod is if your app is not a pure RN app. It is mainly used for this purpose: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html. If you have an existing native iOS app written in Obj-C or Swift, and you want to add a RN component to the app, you use CocoaPods. I don't think there's another time that it is a good idea.

In particular, if you run `react-native link react-native-branch`, the dependencies are already included in the `Libraries` folder in the Xcode project. This applies to all RN SDKs including the `React.xcodeproj` and all its subprojects. At best, if you add CocoaPods, you are compiling two copies of the same thing and adding dead code to the app. At worst, you can get unpredictable results and errors like this. I'm not sure that your error is exactly consistent with this configuration. I would expect a conflict with `libRNBranch.a`, not `libBranch.a`, in case you also used `react-native link react-native-branch`.

One reason I think there may be a problem like this is: If that is your entire Podfile, I don't expect your app to work. In particular, you usually need to add a number of `subspecs` to the `React` pod. See https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies. Also see the [webview_example_native_ios](https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/master/examples/webview_example_native_ios) and [testbed_native_ios](https://github.com/BranchMetrics/react-native-branch-deep-linking/tree/master/examples/testbed_native_ios) projects in this repo for working examples of native apps that embed a RN component and use CocoaPods. At a minimum, your Podfile should contain something like this:

```Ruby
platform :ios, "8.0"

pod "React",
  path: "node_modules/react-native",
  subspecs: %w{
    Core
    RCTAnimation
    RCTImage
    RCTText
    RCTNetwork
    RCTWebSocket
  }
pod "Yoga", path: "node_modules/react-native/ReactCommon/yoga"
pod "react-native-branch", path: "node_modules/react-native-branch"
pod "Branch-SDK", path: "node_modules/react-native-branch/ios"

target "testbed_native_ios" # This should be the name of your app target in your project
```

If you also have the `React.xcodeproj` in the `Libraries` folder, you have duplicate code, but if you omit the subspecs in the Podfile, those libraries (Core, RCTAnimation, etc.) will be supplied by the `React.xcodeproj`. So your app may accidentally work.

Our CocoaPods instructions are for apps already using the React pod. If your app is a pure RN app, and that is your entire Podfile, I would recommend running `pod deintegrate` to remove CocoaPods from the project and just using `react-native link` to manage your dependencies. At least you can remove `react-native-branch` and `Branch-SDK` from your Podfile and just use `react-native link react-native-branch` for this SDK, which should be easier. If you modify the Podfile, don't forget to run `pod install` again to update the generated code.

I may be mistaken. Maybe you only provided an excerpt, not the entire Podfile, and some of this may be irrelevant. But it could result it a problem like this, so it's worth checking.

**Comment by chenyanji** [comment]
@jdee 
My app is not a pure RN app.

Now in Xcode run no error found but run on the terminal react-native run-ios Can not read property 'ADD_TO_CART_EVENT' of undefined error

I recommend finishing a copy of the installation and use of the document。

Usage:

import branch, {
    AddToCartEvent,
    AddToWishlistEvent,
    PurchasedEvent,
    PurchaseInitiatedEvent,
    RegisterViewEvent,
    ShareCompletedEvent,
    ShareInitiatedEvent
} from 'react-native-branch'

Is it correct?

**Comment by jdee** [comment]
**Short Answer:**

- That JS excerpt is correct.
- The docs need improvement and will be totally rewritten as part of the upcoming prod release of 2.0.0. We'll prioritize that.
- This is the first time we've heard of anyone using react-native-branch in an app that is not a pure RN app. Support has been added only recently for this use case, in 2.0.0. It may be incomplete, but we'll be happy to make whatever changes are required if we can understand the issues.
- You don't need to use the RN CLI when integrating with a native app. You can just add a couple of build phases to your project (see below).

**Long Answer:**

The error you report suggests that it's not finding the native module. The native module (iOS or Android) exports the ADD_TO_CART_EVENT constant to JS, and JS exposes that as `AddToCartEvent` from the SDK. I've seen this sort of error reported in unit tests when the native module is not mocked. I don't know why it would happen here.

But I think I probably still don't understand your use case very well. Honestly, it's entirely possible that this repo doesn't support your use case entirely. We'll be happy to make whatever changes are necessary to support that use case, but we'll probably need your help understanding what needs to change.

I'm not sure how `react-native run-ios` is expected to work in a case like this. For example, if I try to run `react-native run-ios` in the `webview_example_native_ios` project, it fails, probably because the iOS code does not reside in a subdirectory called `ios`. Speaking as a native iOS app developer, if I wrote a Swift app and then was asked to integrate a RN component, if RN required me to restructure my app by putting my source code somewhere else, I would simply refuse to use RN. I'm sure Facebook thought of that, and I doubt they intend that a native app should be restructured in order to use one pod. The `testbed_native_ios` and `webview_example_native_ios` apps reflect this assumption and do not put the native code anywhere special. They only add a package.json, some Run Script Build Phases, a bit of JS source for the RN component and some native code to use the RCTRootView. I would not expect to use the RN CLI in this situation at all, and I would not expect it to work. Having said that, I see [here](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html):

"This page only applies to projects made with react-native init...."

I don't understand how an existing app would have been made with `react-native init` unless it was already a RN app. I'll have to read more. But in a native app like `webview_example_native_ios`, I would not expect to run, test, build or distribute my app in a special way because of a dependency any more than I would expect to use special tools for ordinary tasks because I'm using the Cartography pod.

If the reason you want to use the RN CLI is to do things like start the React packager and bundle the JS source, you can accomplish that by adding two Run Script Build Phases to your Xcode project. This has been done in both `testbed_native_ios` and `webview_example_native_ios`. Add:

**Start React Packager** (Run Script Build Phase)
```bash
if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
if nc -w 5 -z localhost 8081 ; then
if ! curl -s "http://localhost:8081/status" | grep -q "packager-status:running" ; then
echo "Port 8081 already in use, packager is either not running or not running correctly"
exit 2
fi
else
open "$SRCROOT/node_modules/react-native/packager/launchPackager.command" || echo "Can't start packager automatically"
fi
fi
```

**Bundle React Native code and images** (Run Script Build Phase)
```bash
export NODE_BINARY=node
node_modules/react-native/packager/react-native-xcode.sh
```

<img width="708" alt="screen shot 2017-07-26 at 11 27 16 am" src="https://user-images.githubusercontent.com/121951/28637182-8735198e-71f5-11e7-8021-41fd043ba017.png">

This has nothing at all to do with Branch. This is just a solution for integrating RN with a native app. I haven't found any documentation for how to do this. I took those build phases from `React.xcodeproj` in a project made with `react-native init`. I'm sure we can improve on that. We can recommend this in our docs, but we assume you've already solved this problem when integrating RN with your app in the first place.

Much of this seems obvious to me and seems like it would be obvious to other native app devs, so I'm afraid that what I've described does not reflect what you're doing. Or maybe I've just made some poor assumptions. Either way, we still have work to do. If you're interested in helping us understand what you are doing in some detail and what changes you need, we'll be quite happy to support you. Anyway, I'll research the issue further, since clearly we aren't finished here. I apologize for the difficulties you've experienced. I'm an app developer too, and I know what it's like to try to use a dependency that doesn't work well. We'd like to make things easier for you.

**Comment by chenyanji** [comment]
@jdee 
Thank you, now I can already generate a short connection on the real machine.

I have another question is how do I get the app after the installation is completed by the short link to carry the parameters?

Get the parameters by:
  Branch.subscribe (({error, params}) => {
             If (params &&! Error) {
                 // grab deep link data and route dim.
                 Alert.alert (params);
             }
         })

How do I have not released a new version of app for debugging?

**Comment by chenyanji** [comment]
@jdee Thank you very much, I have got the answer from the example #

**Comment by CorinneKelly** [comment]
I'm having a similar problem, however the my app IS a pure react native app, im using 
"react-native-branch": "^2.0.0-rc.2",
"react-native": "0.46.0",
and am following [these]('https://dev.branch.io/getting-started/sdk-integration-guide/guide/react/') instructions 
![error message:](https://user-images.githubusercontent.com/14987158/29837442-20db7b4c-8cc6-11e7-8e3e-0cb9c15f4a46.png)

I've tried using react-native link react-native-branch, I tried linking manually, I also tried adding a podfile but I'm still getting the same error.

**Comment by chenyanji** [comment]
@CorinneKelly I also encountered this error before, and then I used Carthage installed to solve the problem

**Comment by CorinneKelly** [comment]
@chenyanji thanks but my app is a pure react native app - I don't currently have any podfiles, so I'm not sure that installing Carthage will solve my problem

**Comment by chenyanji** [comment]
@CorinneKelly No podfiles will be a problem, it is recommended to use Carthage installation

**Comment by jdee** [comment]
Carthage is not supported with version 2.0.0. With 2.0.0 you must take the Branch native SDKs from the NPM module. That includes the case when using the React pod in a native iOS app.

@CorinneKelly Did you just add this SDK to your app? Or did this start happening on upgrade? The instructions on the docs site need to be updated but should be accurate. However, this repo's README was just updated. The installation and setup instructions are current and accurate.

Also, in the future, please report problems integrating the app to integrations@branch.io or open a ticket in the support portal. Please use repo issues for reporting bugs in the SDK. Thanks.

**Comment by CorinneKelly** [comment]
i just added this SDK, but ill open a ticket in the support portal, thanks!
