### ISSUE TITLE
How to add pictures to share

### ISSUE THREAD

**Issue by chenyanji** [BranchMetrics/react-native-branch-deep-linking#237]
![image](https://user-images.githubusercontent.com/8857201/29239506-be7944b6-7f82-11e7-9f85-258135eb6274.png)

![image](https://user-images.githubusercontent.com/8857201/29239524-162cb922-7f83-11e7-9cf1-3cc5f006b662.png)

react-native-branch：2.0.0-beta.8
@jdee

**Comment by jdee** [comment]
Please contact integrations@branch.io for assistance with integrating the SDK. You can also find people there who can communicate in languages other than English and can probably assist you better. Please use issues in this repo to report bugs with this SDK.

Also please see the examples in this repo, particularly webview_example, which does exactly what you want. However, I immediately see a problem. The title, description and image URL should not be specified as link properties. They are specified at creation of the Branch Universal Object. Here is an example:

https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/Article.js#L38

(That method should probably be called in componentDidMount rather than componentWillMount. But that's where you specify the contentImageUrl.)
