### ISSUE TITLE
setup instructions outdated for release 2.0

### ISSUE THREAD

**Issue by twairball** [BranchMetrics/react-native-branch-deep-linking#240]
You guys probably have it on a todo list but thought i'd just point out!

setup instructions in 
`https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/setup.md`
in correctly has for `AppDelegate.m`:

````
// Add the openURL and continueUserActivity functions
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    if (![RNBranch handleDeepLink:url]) {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
        return YES;
    }
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
    return [RNBranch continueUserActivity:userActivity];
}
````

while `examples/testbed_simple` has working setup:

````
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  if (![RNBranch.branch application:application openURL:url sourceApplication:sourceApplication annotation:annotation]) {
    // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
  }
  return YES;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
  return [RNBranch continueUserActivity:userActivity];
}
````

**Comment by twairball** [comment]
... now that I'm done checking the android parts, the `MainApplication.java`, `MainActivity.java` and `AndroidManifest.xml` also have discrepancies between the `setup.md` and `examples/test_bed_simple/android`

**Comment by jdee** [comment]
Thanks for this. The docs are being rewritten. That will be complete soon.

**Comment by twairball** [comment]
While we are here, I've picked up some `info.plist` keys e.g. `branch_universal_link_domains` and `branch_app_domains` that don't seem to be documented on the react-native or iOS SDK repo readmes. Are they used for custom domains only?

Hope that helps and thanks for the replies.

**Comment by jdee** [comment]
I think the key is called `branch_app_domain`. One reason I'm not sure what it's called is that I know it's not used. The `branch_universal_link_domains` key is used with custom domains and non-Branch domains for morphological identification of Branch links. The SDK automatically recognizes app.link subdomains and bnc.lt. For any other domain, `[Branch continueUserActivity:]` will by default return NO instead of YES. The SDK also consults the `branch_universal_link_domains` key for additional domains to be handled. That key is documented here: https://dev.branch.io/getting-started/universal-app-links/advanced/ios/.

There is also some automation available to help set up and validate your project configuration using Fastlane: https://github.com/BranchMetrics/fastlane-plugin-branch. This is used with the example apps in this repo. The Android support in the plugin is not very mature, but it can automatically set up all the configuration in your Xcode project. It can also validate the Universal Link configuration for any Xcode project, whether it uses Branch or not.

**Comment by twairball** [comment]
Thanks for the reply, but I'm still not clear whether I need to set it or not?

**Comment by jdee** [comment]
@twairball If you are using a custom domain for your Branch links (not *.app.link) or if you are using Branch to handle your own non-Branch domain (example.com) you should set the `branch_universal_link_domains` key.

2.0.0 has been released. The README has been rewritten. Closing this issue. Thanks for all the feedback.
