### ISSUE TITLE
[Android] JS objects not supported as metadata, JSON metadata is incorrectly escaped

### ISSUE THREAD

**Issue by computerjazz** [BranchMetrics/react-native-branch-deep-linking#260]
Setting a metadata param to a stringified JS object results in an incorrectly-escaped link.
On iOS, metadata params can be directly set to JS object and can be retrieved with no issues.
However, objects are not directly supported on android and must be stringified 
[(there is no case for objects here and a JS object will receive a value of "unsupported type")](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/android/src/main/java/io/branch/rnbranch/RNBranchModule.java#L709-L722)

Originally reported in Cordova SDK: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/133#issuecomment-327849377

code:

```javascript

    const user = {
    name: 'computerjazz'
}

    let branchUniversalObject = await branch.createBranchUniversalObject(
        'content/12345', // canonical identifier
        {
          contentDescription: 'Testing!',
          metadata: {
            testParam: JSON.stringify(user),
          }
        }
      )

    let linkProperties = {
      channel: 'internal',
    }

    let controlParams = {
      '$desktop_url': 'http://www.example.com',
      '$ios_url': 'example://',
      '$android_url': 'example://',
    }
    let { url } = await branchUniversalObject.generateShortUrl(linkProperties, controlParams)
    return url
```

result:

![screen shot 2017-09-07 at 10 46 35 am](https://user-images.githubusercontent.com/6730148/30177188-e5797fea-93b9-11e7-914e-cd7709485dbb.png)

**Comment by jdee** [comment]
The short answer here is that only strings are supported for metadata values, and the fact that other types work on iOS is not entirely intentional. That will stop working in the near future, with some planned changes in the Branch system and the iOS SDK.

What you're doing for Android, with `JSON.stringify`, is correct. I can see that something is being serialized in an odd way though. The string returned by the SDK should not be escaped. I'll fix that and release a patch.

**Comment by calebfoster** [comment]
@jdee I ran into this problem as well, also tried `JSON.stringify` and discovered that weird serializing issue. So I dove into Android source to try and come up with a fix. How quickly do you think you'll have a fix.. should I continue to search one myself? I'm looking to supply an update to my app asap and this is the outstanding issue. Thanks

**Comment by computerjazz** [comment]
@calebfoster I'm using this workaround and it's doing the trick for now: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/133#issuecomment-215752681

**Comment by calebfoster** [comment]
@computerjazz what exactly are you doing to fix it?

**Comment by jdee** [comment]
So far I can only tell you that this happens during serialization on the Android side. You can pass stringified JSON when creating links on iOS and open those links just fine on Android. I think I verified that everything was coming through just fine from RN (the ReadableMap object that is passed to Java). So it's likely a question of the Android SDK doing something to the input. The workaround recommended by @computerjazz looks like the right thing to do. I'll see if I can get that released quickly.

**Comment by sojanpr** [comment]
@computerjazz as we embed the data portion of the link payload inside another json, it's nested and therefore double encoded.
Do you think either of the following  can help you to fix the issue
1. Using JSonObject
    Convert the escaped string to  a JsonObject and covering to back to string
    `String orginalvalue = new JSONObject("{\"key\":\"value\"}").toString();`

2) Using an apache lib
 From your build.gradle, include compile 'org.apache.commons:commons-lang3:3.4' -- in activity just call currentStringWithSlashes = StringEscapeUtils.unescapeJson(currentStringWithSlashes) and you'll have the String as you sent it off.

**Comment by computerjazz** [comment]
@calebfoster 

```javascript
branch.subscribe(bundle => {
    if (bundle && bundle.params && !bundle.error) {
      // grab deep link data and route appropriately.
      if (bundle.params.yourCustomParam) {
        // Fix branch issue on android that double-escapes strings
        if (typeof bundle.params.yourCustomParam == 'string') {
          const __unescaped = bundle.params.yourCustomParam.replace(/\\/g, "");
          bundle.params.yourCustomParam = JSON.parse(__unescaped);
        }
       // now you can do stuff with bundle.params.yourCustomParam
      }
    }
  })
```

**Comment by jdee** [comment]
We haven't forgotten about this, but a workaround in the RN SDK is not that easy. As @computerjazz showed in the original post, the problem seems to happen at link creation on Android. Links like that will not return the correct metadata in any Branch SDK. If we work around this in this SDK, it also has to be done in the iOS SDK, the web SDK, Cordova, Titanium, Unity, etc. Not to mention that metadata keys have to be identified separately. Just replacing every backslash in every field is probably not safe. It would have to be something along these lines:

```js
for (key in params) {
  const param = params[key]
  if (/^~/.test(param) || /^\+/.test(param) || /^\$/.test(param)) continue

  const unescaped = param.replace(/\\/g, '')

  try {
    // only do this if the unescaped param is parseable as JSON
    JSON.parse(unescaped)
    params[key] = unescaped
  }
  catch (error) {
    // not JSON, do nothing
  }
}
```

I believe this is an issue in the Android SDK, and the right answer is probably to patch the Android SDK and include the updated SDK here. This is under review with the Android team and will happen quite soon.

For the moment, if you can live with working around this in app code as indicated above, that's probably best. It will improve in the next release. Apologies for the delay.

**Comment by sequoiaat** [comment]
@computerjazz  Hello, Hope it is clear now. Can we close the issue ?
