### ISSUE TITLE
CRASH - java.lang.NullPointerException - BranchUrlBuilder.java:58

### ISSUE THREAD

**Issue by eneskaya** [BranchMetrics/react-native-branch-deep-linking#274]
Hello, I'm getting more and more of this in my crash reporting:

```
java.lang.NullPointerException Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
```

The exception is `java.lang.NullPointerException - BranchUrlBuilder.java:58`

I'm on version 2.0.0

**Comment by sequoiaat** [comment]
Hello,
 This error may occur due to incorrect generateShortUrl() method usage or incorrect declaration/creation of BUO/link properties. 
From the error description, we are not able to identify it. Its good if you can provide us more information like:
•	React native and branch versions .
•	Configurations you have used.
•	Does it occur consistently or occasionally?

**Comment by eneskaya** [comment]
As this issue is a bit older consider closing it as invalid. The project i set this up in doesn’t exist anymore and I cannot provide more information on it. Thank you anyway.

**Comment by sequoiaat** [comment]
Ok. Thank you for letting us know.
