### ISSUE TITLE
Branch Link doesn't survive Login Page

### ISSUE THREAD

**Issue by thisisjaiswal** [BranchMetrics/react-native-branch-deep-linking#323]
Branch is osome. It handles hundreds of use cases to give a smooth deep link experience. but one think I found hard to implement is to make it work with login page. and I dint find a good example for it either.

When a user clicks a branch link, it reaches to the exact content of the app even surviving app install. but when there is a login page (I used Social Logins) there is no easy way to make it "wait till user is logged in" 

how to use branch.subscribe in login page ?
if user is logged in and branch is clicked then open the content. 
if user is logged in and branch is not clicked open home page
if user is not logged in and branch is clicked show login page and on login open the content.

I tried to implement it using getLatestReferringParams (on start) + subscribe (rest of the time)
It worked. but not consistent.
On iOS - Facebook login works but Google login doesn't.
on Android - Google login works but Facebook doesn't.  

I wasted 3 days to get this working correctly.. no luck

**Comment by dani-sc** [comment]
I just subscribe at the very start of my app. If the app was opened via a link, I handle two cases:
1. The user is logged in: Fine, let's just route the user to the appropriate screen.
2. The user is not logged in: Let's manually cache the params of the url. When the user is logged in, I'll check if there are params in my cache - if there are, I'll now route the user to the appropriate screen.

**Comment by sequoiaat** [comment]
Hello,
We have few enhancements related to it in latest version 2.2.5 . Can you please try it and let us know the status?

Thanks

**Comment by Jonovono** [comment]
@sequoiaat what would you recommend to solve this? Can you point to the changes in 2.2.5 for this? Thanks!

@thisisjaiswal how did you end up solving it?

**Comment by sequoiaat** [comment]
@Jonovono  This issue happens due to change in launch url when it comes back from the social login app and old url is overwritten with the new one.
The solution @thisisjaiswal had tried (getLatestReferringParams (on start) + subscribe) is best for this case, but since there was an issue with getLatestReferringParams, it might have been inconsistent.

We had delivered a fix for the getLatestReferringParams issue in iOS and also fixed the subscribe timeout issue. it is now published as 2.2.5.
Can you to try the same solution with latest version.
 
Can you please try to keep old launch url in memory on the login page and later reuse if login is successful.

**Comment by sequoiaat** [comment]
Hope this is ok now. We are closing it, please re-open if you are facing any issue.
