### ISSUE TITLE
Trouble getting deferred deep link working

### ISSUE THREAD

**Issue by stefanlenoach** [BranchMetrics/react-native-branch-deep-linking#342]
I'm trying to get deferred deep linking working but have run into some problems. In my top level file I create a subscriber like so:
```
branch.subscribe(({error, params}) => {
  console.log(params)
})
```

When I click a deep link after installing the app I get something like this:
```
{ '+is_first_session': false,
'+clicked_branch_link': false,
'+non_branch_link': 'https://myapp.app.link/ewf23...' }
```

When I try to do deferred deep linking via click link -> install -> open app, I get this:
```
{ '+is_first_session': false,
'+clicked_branch_link': false,
cached_initial_event: true }
```
This suggests that branch did in fact cache something but I don't see anywhere in the documentation how to retrieve this info. I tried doing `branch.getLatestReferringParams()` and `branch.getFirstReferringParams()` but neither of these methods were able to give me back the link url:
`latestParams = { '+is_first_session': false, '+clicked_branch_link': false }`
`firstParams = {}`

I can't tell what's wrong and was hoping someone could point me in the right direction. Thanks!!

**Comment by blastering66** [comment]
Mee too... for me it happens on ios only.

**Comment by Jonovono** [comment]
I seem to also get this. 

@sequoiaat what is the expected behaviour? If I call subscribe in one component and then later call subscribe again on a different view should they both see the initial params?

**Comment by sequoiaat** [comment]
The expected behaviour is, if we're clicking a branch link then we get {'+is_first_session': false,
'+clicked_branch_link': true,{{the referring link and with parameters if any}}}.

For e.g., {"~referring_link":"https://ms9y.test-app.link/axXS9n5XZM","+click_timestamp":1526579796,"$identity_i
d":"518347959956831852","source":"android","$og_image_url":"https://upload.wikimedia.org/wikipedia/commons/e/e5/Venus-real_color.jpg","~creation_source":2,"$deeplin
k_path":"en.m.wikipedia.org/wiki/Venus","$canonical_identifier":"planet/Venus","$publicly_indexable":"true","$ios_deepview":"branch_default","$canonical_url":"https
://en.wikipedia.org/wiki/Venus","~channel":"Copy","$og_title":"Venus","+match_guaranteed":true,"prop2":"abc","prop1":"test","~feature":"share","$rating_average":4.2
,"$desktop_url":"https://en.wikipedia.org/wiki/Venus","$one_time_use":false,"$android_deeplink_path":"en.m.wikipedia.org/wiki/Venus","+is_first_session":false,"+cli
cked_branch_link":true,"~id":"525720443693736678"}.

**Comment by sequoiaat** [comment]
Hope this is ok now. We are closing it, please re-open if you are facing any issue.

**Comment by salmanbukharihitori** [comment]
I am facing this issue still. The one and only response that I get is this: 

{params: {…}, uri: null, error: null}
error: null
params:
+clicked_branch_link: false
+is_first_session: false
__proto__: Object
uri: null
__proto__: Object

**Comment by sergiulucaci** [comment]
@stefanlenoach @blastering66 @Jonovono I am facing a similar issue, did you finally manage to make it work?

**Comment by ahoang** [comment]
I am having a similar issue, if the user does not have the app installed, they are redirected to the App Store first (correctly), then when they open the app and I check the referring params, it is nil. 2nd time the user opens the app, the referring params are there.
