### ISSUE TITLE
Branch.subscribe does not fire from deep link when app is closed

### ISSUE THREAD

**Issue by AdamPD** [BranchMetrics/react-native-branch-deep-linking#367]
Hi there,

We are using Expo to integrate with Branch.  Everything seems to be working except that `Branch.subscribe` does not fire when opening a deep link if the app is installed but completely closed.

My code is:

```
componentDidMount() {
        this.unsubscribeBranch = Branch.subscribe(({ params }) => {
            Alert.alert("", JSON.stringify(params));
        });
    }

    componentWillUnmount() {
        if (this.unsubscribeBranch) {
            this.unsubscribeBranch();
            this.unsubscribeBranch = null;
        }
    }
```

If the app is already open and the link is tapped, then this works fine.  But if the app is closed, the subscribe does not provide the initial event.

More interestingly, if I run `Branch.getLatestReferringParams` in the `componentDidMount` (after the subscribe), I do receive the correct link information.

This is using the latest Expo SDK (29), iOS 11 on an iPhone X.

The component is only mounted once and is mounted almost straight away after some initialisation code.

I'm a bit stuck here as this is crucial to our implementation.

**Comment by sequoiaat** [comment]
@AdamPD   We are working on replicating the issue . We will revet back with an answer to help you move forward

**Comment by sequoiaat** [comment]
@AdamPD  one observation In the code, inside componentDidMount() function you just put an alert and no routing is found(i.e., where to pass this param or to navigate to which page).

We tried to replicate but we got the expected behavior and fires the app and we get the parameters.   This is the URL for reference -
 https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/ArticleList.js#L37 

we will try it via expo and see if we are able to reproduce the issue you are facing.

**Comment by AdamPD** [comment]
@sequoiaat - thanks for looking into it.  I have narrowed it down to an Expo issue.  Expo has made some reasonably significant adjustments to the initialization code for Branch to accommodate Expo's unique nature (i.e. having multiple SDKs supported in a single app, etc.).

When detaching from Expo (even with their initialization code changes, which is even more strange), the behaviour is as expected.

I've created a relevant issue for Expo (https://github.com/expo/expo/issues/2085) so I imagine you can close this issue.
