### ISSUE TITLE
[Android] Update readme config for RN 0.30+

### ISSUE THREAD

**Issue by mlumbroso** [BranchMetrics/react-native-branch-deep-linking#38]
Hello,

instructions on MainActivity.java are out of date, it should now use MainApplication.java  

Plus, using the override on this file throws errors. Can you please update instructions for Android?

Thanks

**Comment by rseemann** [comment]
Any news on this? This is blocking me from using the library at all.

**Comment by rt2zz** [comment]
The change basically requires putting the RNBranchPackage in MainApplication instead of MainActivity. I [updated the docs](https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/setup.md#android-project) accordingly. Can you give that a shot and let us know if anything is confusing. We are always looking for ways to improve the docs.

**Comment by rseemann** [comment]
@rt2zz After some trial and error messing around that's the same result I got it, it seems to work.

Thanks!

**Comment by aaustin** [comment]
Great ! 👍
