### ISSUE TITLE
getFirstReferringParams and passive deepview on iOS

### ISSUE THREAD

**Issue by f19yd** [BranchMetrics/react-native-branch-deep-linking#416]
Hello,

I get a really strange bug with getFirstReferringParams.

If I disable Deepviews Passive I get all params of link clicked before install app.

But If I active deepviews I get only {\"+clicked_branch_link\":false,\"+is_first_session\":true}

`
[branch.io] BNCServerInterface.m(822) Debug: Server returned: Status: 200; Data: {
    data = "{\"+clicked_branch_link\":false,\"+is_first_session\":true}";
    "device_fingerprint_id" = 625830893445498417;
    "identity_id" = 625830893453867382;
    link = "https://appourco.test-app.link?%24identity_id=625830893453867382";
    "session_id" = 625830893457956946;
}
`

I missed something ?

**Comment by csalmi-branch** [comment]
@f19yd Can you double check you are using the same keys for link creation and in the app?

Can you also double check your passive deepview template since the default is different from the active deepviews?

If neither of those seem to resolve the problem, please let us know what version you are using, and whether this is on iOS, Android, or both.

**Comment by f19yd** [comment]
@csalmi-branch i found my error. I was enable a deepview.
If i disable all deepview and set only my passive deepview all working.
Thanks for you time
