### ISSUE TITLE
setDebug not working

### ISSUE THREAD

**Issue by skleest** [BranchMetrics/react-native-branch-deep-linking#58]
Hi,

Branch documentation says setDebug() will simulate fresh installs but it is not working--is there a way to simulate fresh install? Thank you.

**Comment by rt2zz** [comment]
can you share a snippet of how and where you are calling setDebug?

**Comment by skleest** [comment]
Definitely--
Adding following to index.js componentdidmount:

// Subscribe to incoming links (both branch & non-branch)
branch.subscribe(({params, error, uri}) => {
  if (params) { /* handle branch link */ }
  else { /* handle uri */ }
})

branch.setDebug();

**Comment by aaustin** [comment]
Hey @skleest - A couple questions:
- Which platform are you testing this on? Android might need a different treatment
- Have you tried calling it before subscribe?

Thanks much!

**Comment by skleest** [comment]
Hi @aaustin, 

- "react-native": "^0.25.1", iOS only currently
- "react-native-branch": "^0.8.0",
- OSX

Also tried calling it before subscribe in componentDidMount and even outside createClass (on top with import statements).

Both branch keys are in info.plist
<img width="370" alt="screen shot 2016-11-23 at 11 40 51 am" src="https://cloud.githubusercontent.com/assets/13384462/20576186/b99e3cec-b171-11e6-9034-80e5398982ec.png">

Only live key is being used (links created in test mode don't get tracked) and therefore cannot get it to show fresh install referral. Thank you!

**Comment by rt2zz** [comment]
In order to setDebug you will need to call setDebug [*before* branch inits](https://dev.branch.io/getting-started/integration-testing/guide/ios/#use-debug-mode-to-simulate-fresh-installs). Essentially you will need to put the setDebug call in AppDelegate roughly as follows:

```
[RNBranch setDebug];
[RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```

Presumably you will want to contextually set setDebug based on RCT_DEV (or some other flag)
```
#if RCT_DEV
  NSLog(@"Application received local notification: %@", notification);
#endif
```

Let me know if that helps

**Comment by skleest** [comment]
Thanks for the reply @rt2zz .

Your suggestion seems to be from iOS documentation?
The [RN documentation](https://dev.branch.io/getting-started/integration-testing/guide/react/) does not have setdebug call in appdelegate (), and it actually produces error: No known class method for selector 'setDebug'.

**Comment by rt2zz** [comment]
@skleest indeed, my mistake. RNBranch.setDebug is supported on both platforms. 

This appears to be a bug, wherein RNBranch eagerly initializes, so by the time you call setDebug, the init session has already been processed.

**Comment by skleest** [comment]
Got it, thank you @rt2zz!

**Comment by GeoffreyPlitt** [comment]
Is this getting fixed? We basically can't QA installs.

**Comment by jdee** [comment]
@GeoffreyPlitt This is one of the numerous other reasons it will be nice to refactor the SDK to allow initialization of the native Branch SDK after the JS loads. This is basically a docs issue. With #205, `setDebug()` now throws with a link to this [doc](https://rnbranch.app.link/hGj7E61EhD).

A general rewrite of the docs is part of the 2.0 release. I've been putting it off until the most radical changes to the SDK were finished, in order to avoid serial rewrites. I should be able to have at least a first draft next week.

Since the workaround is now documented, I'm closing this issue.

**Comment by GeoffreyPlitt** [comment]
Thanks Jimmy! Are you tracking that new work in an issue or PR or something so I can subscribe to it?

**Comment by jdee** [comment]
@GeoffreyPlitt  I've opened #206. I think there might be a middle-of-the-road solution that would be doable in 2.0.0. Any thoughts are welcome.

**Comment by GeoffreyPlitt** [comment]
Cool, thanks!
