### ISSUE TITLE
[android] deep link only works with facebook posting

### ISSUE THREAD

**Issue by good2hear** [BranchMetrics/react-native-branch-deep-linking#64]
Hi, 
I worked on implementing android deep link while waiting for iOS deep link issue with facebook.

and now it's different scenario..
It only works when tapped from facebook share posting (unlike iOS) 
 - when xxxx.app.link was used, app opens but does not transition to desired page 
 - when my website link was used to redirect xxxx.app.link, app opens and transition works fine!

when I tested with other options (e.g. e-mail, sms, slack so far), it always goes to play store even if app is installed on my device.. (tried both app.link url and website url; results are the same) 

I haven't implemented app links but that shouldn't be a problem 

has anyone encountered similar problem?
any comments will be appreciated!!
thanks!!

**Comment by good2hear** [comment]
looks like normal behavior for android..
please feel free to re-open if anyone finds out!

**Comment by rt2zz** [comment]
Sorry for the delay, what you described does not sound like intended behavior. In particular I think setting up app links might solve part of the problem here (make sure you have the SHA256 Cert Fingerprints correct)

Where you describe that the link routes correctly when clicked from chrome but incorrectly if clicked from FB makes me think this may be an issue with how you are configuring and routing the links. Can you log and verify that the payload being received by your `branch.subscribe` listener looks correct with whatever data you have attached?

**Comment by good2hear** [comment]
@rt2zz thanks for reply!! will do some debugging; try with app links!
