### ISSUE TITLE
Content preview CTA sometimes fails on iOS

### ISSUE THREAD

**Issue by ninjz** [BranchMetrics/react-native-branch-deep-linking#82]
We are hosting our own content previews, and using the web SDK's deepview() and deepviewCta() functions for deep linking. The "view in app" button is triggering the deepviewCta() function successfully on Android, but on iOS, the user is sometimes taken to the app store even when the app is installed (clicking "open" from the app store page successfully routes to the deep link path).

After speaking with Branch support, it seems as though linking through https://[branchdomain].app.link works correctly, but linking through https://[branchdomain]-alternate.app.link opens the App Store. We have confirmed that our Xcode associated domains include both [branchdomain].app.link and [branchdomain]-alternate.app.link.

We have been working with @ethanneff on this issue, and attached is a testing video showcasing the issue. as you can see that the CTA fails on https://seecows-alternate.app.link and opens up the App Store.

![iaepb16 - imgur](https://cloud.githubusercontent.com/assets/5641860/22166863/3d4dcad4-df31-11e6-95c5-214251a80c86.gif)

**Comment by jdee** [comment]
@ninjz @ethanneff You've probably already checked this, but there is some peculiar iOS behavior with Universal Links and App Store redirects. Once the user taps the "app.link" breadcrumb on the right side of the status bar, iOS will always take the user to Safari for that domain until the user redirects that domain back to the app. This works fine with a deep link to content, e.g. a mobile web page that has a native representation in the app. Then the user can choose whether they prefer the web or the app. Safari will show a Smart Banner for those pages (the user has to pull the page down to expose it) with a button to open the link in the app instead. After that, links will be directed into the app until the user taps the breadcrumb again.

Unfortunately this doesn't work as well with App Store redirects. Safari doesn't show a page with a Smart Banner for an App Store redirect. It just redirects immediately to the App Store app. The user has no way of telling iOS to open the app instead of Safari once they've tapped the breadcrumb. The only way I know to get out of that state is to e-mail yourself a deep link to the problem domain, open the message in the Mail app and then long press the link. This will show a menu with an option to open in the app. Once you do that, links to that domain will be opened in the app again (until the user taps the breadcrumb again).

As far as iOS is concerned, the two app.link domains are distinct. So seecows-alternate.app.link URLs may be directed to Safari, while seecows.app.link URLs are opened in the app.

However, this would not be consistent across devices and users, and the behavior could just as easily occur for the main domain as the alternate.

This could be part of the problem anyway.

**Comment by ethanneff** [comment]
@jdee,

Thank you for the response. The .gif from @ninjz from my testing. Unfortunately, this issue is not related to the breadcrumb redirect on iOS where you can disable Universal Links on the device.

Whenever a user navigates from a Branch Deep View from an app.link link domain, Branch uses another subdomain to navigate into the app. This is why we recommend our users to add  2 values in their Associated Domains for the iOS Branch SDK.

```sh
applinks:ethan.app.link 
applinks:ethan-alternate.app.link # used for Deep Views
```

![image](http://i.imgur.com/67t6hSY.png)

Since I have not implemented the React Native Branch SDK yet, can you confirm these values are being added into the Associated Domains from the React Native Branch SDK?

Regards,

**Comment by rneilson** [comment]
@ethanneff @jdee Sorry for the delay. We can confirm the alternate domains are included in the Associated Domains, yes.

**Comment by jdee** [comment]
@rneilson I double-checked the apple-app-site-assocation file for each domain (generated by Branch). The results are the same from the two domains:

```json
{"applinks":{"apps":[],"details":[{"appID":"9JP76YLRW6.com.seecows.SEECOWS","paths":["NOT /e/*","*","/"]}]}}
```

The SDK is not involved when the operating system opens the app from a Universal Link. You don't even have to have the Branch SDK installed for that part to work. All that should be required is to add the `applinks:` entries under Associated Domains.

Here's something you can try:

1. Create a new Hello World app with Xcode. (Use File > New > Project... and select Single View Application).
2. Give it your bundle identifier (com.seecows.SEECOWS) under Identity on the General tab for the project.
3. Specify your team under Signing on the same tab.
4. Add the `applinks:` entries under Associated Domains.
5. Build, deploy and run on a device.
6. Try and open any link to seecows.app.link or seecows-alternate.app.link on the device. 

The Hello World app won't be able to do anything interesting without the SDK, but you should be able to open the Hello World app from links to both domains.

Another thing to check is the device console log, using Xcode while your device is plugged in. Go to Window > Devices and select the device. If the console log is not showing, you can open it using a small button near the bottom:

<img width="985" alt="screen shot 2017-02-02 at 1 07 04 pm" src="https://cloud.githubusercontent.com/assets/121951/22568465/cdc35b08-e948-11e6-9ba9-545a81ecceb2.png">

That should reveal a console like this:

<img width="985" alt="screen shot 2017-02-02 at 1 07 00 pm" src="https://cloud.githubusercontent.com/assets/121951/22568542/08b7febc-e949-11e6-8579-8bc4f559131c.png">

If you click there, you can use cmd-F to search.

There's a server process on iOS called swcd that manages the domain associations. Whenever you install an app (including every time you build and deploy with Xcode), swcd crawls the AASA files for those domains. It should provide some feedback on whether it accepts or rejects each domain. If the `-alternate` domain is being rejected, you should see something there. Just search for swcd after you deploy a build to the device.

Finally, there's the question of where Branch is redirecting. You should be able to see the redirect URLs for the link in the Liveview & Export section of the Branch dashboard. I'm not sure if you can search there, but if you create new links, they should be visible at the top.

**Comment by jdee** [comment]
I keep thinking about this, and there are really very few possibilities for what's wrong here because of how Universal Links work. The OS maintains a list of verified app-domain associations on the device. When you open a Universal Link in the app, there's not even a need to use the internet in principle. The OS sends the user directly into the app via the domain association. Branch is not involved in the process of opening a link until the app receives the link via [UIApplicationDelegate application:continueUserActivity:restorationHandler:] and passes the link to [RNBranch continueUserActivity:].

So if a Universal Link is not directing into the app, I think there are only two possibilities:

A. The domain association is wrong.
B. The OS is choosing for some reason not to direct the link into the app.

A would mean that the associated domain entitlements were missing from the app or that the AASA file did not check out. But the AASA file is the same for both domains, and since the main domain works, and you've double-checked the domains in Xcode, this seems very unlikely.

B sounds a lot like the breadcrumb issue I mentioned at first. In fact, the solution to that problem is a good test for the domain association. It's very easy:

- Mail yourself a link to the `-alternate` domain.
- Open the message in the iOS Mail app.
- Long press the link in the Mail app until a menu appears.

There should be an option to "Open in Seecows app" or something similar. If there is, the domain association is correct. Select that, and the link should direct into the app. And afterward links to that domain should open the app from Safari or other locations as well.

**Comment by jdee** [comment]
I just installed version 1.0.5 of the Seecows app from the App Store. The following links both open the app:

https://seecows.app.link/ 
https://seecows-alternate.app.link/

I really don't think there's anything wrong with the domain association. I think you just need to do the Mail app exercise above.

**Comment by ninjz** [comment]
@jdee  It looks like the Mail app exercise you proposed did the trick. I don't understand why that issue appeared as I really do not recall having pressed the breadcrumb to begin with. I had an issue before with the original seecows.app.link before as well, and had to do a similar exercise (pasting the link in notes and then holding it to open in app).

If i'm not mistaken, @ethanneff had an issue opening the https://seecows-alternate.app.link/ as well when you first installed the app? Because if that was the case, I would think that is unexpected behaviour, having to paste the link in another app and all. But as of now, after doing the steps on my phone, both the links work now. But i'm curious to know if that by default was what happened to Ethan when he initially installed the app.

**Comment by jdee** [comment]
@ninjz I'm glad that helped. I'm not sure exactly what to say except I feel your pain. I went through that with another app. This aspect of Universal Links is kind of mysterious, and it doesn't always seem to behave the way I'd expect. I wonder if iOS gets confused by subdomains. If Ethan had another .app.link subdomain redirecting to Safari, it's possible that iOS sometimes gets that wrong.

**Comment by ethanneff** [comment]
Hello @jdee,

I apologize. After further testing, the issue seems the isolated to the Web SDK, and not React Native. I am filing a bug report now. @ninjz I have tested your app again and everything seems to be working correctly. @jdee I'm installing the React Native Testbed now, so I will be able to pinpoint the issue better next time. 

Thank you for all your help.

Best,
